# -*- coding: utf-8 -*-
"""join.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OjudUHZHxZTU9PfF911tPdOLlE6S07hC
"""

import pandas as pd

df_alunos = pd.read_csv('/content/Listagem alunos por curso - atual.csv')
df_cr = pd.read_csv('/content/Endereço_CRA_Alunos-teste.csv')

df_alunos.head()

df_cr

df_join = pd.merge(df_alunos,df_cr, left_on='MATR_ALUNO', right_on='MATRICULA')

df_join

columns = ['ID_PESSOA','NOME_PESSOA','SEXO','DT_NASCIMENTO','FORMA_INGRESSO','FORMA_EVASAO','MATR_ALUNO','NUM_VERSAO','PERIODO_INGRESSO','DT_EVASAO','PERIODO_EVASAO','CPF_MASCARA','CRA','BAIRRO','CIDADE','ESTADO']
df_join = df_join.filter(items=columns)

import pandas as pd
!pip install cryptography

tabelaPrinc = pd.read_excel("/content/planilhaJoinCriptografada.xlsx")

tabelaPrinc.head()

tabelaPrinc2 = tabelaPrinc[tabelaPrinc.DT_NASCIMENTO.str.contains("23/04/1999")]

tabelaPrinc2

import pandas as pd
!pip install cryptography

import json

with open('/content/Limite_de_Bairros.geojson') as f:
  bairros = json.load(f)

df = pd.read_excel("/content/planilhaJoinCriptografada.xlsx")

dfgb = df.groupby(['BAIRRO','CIDADE']).size().reset_index(name='ALUNOS')


import plotly.express as px

fig = px.choropleth(dfgb, geojson=bairros, locations='CIDADE', color='ALUNOS',
                     range_color=(0,14)
)

fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()